name: Rust

permissions:
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v6
      - run: rustup toolchain install nightly
      - uses: Swatinem/rust-cache@v2
      - uses: rui314/setup-mold@v1
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: cargo install sqlx-cli
      - name: Generate code coverage
        run: |
          sqlx migrate run
          cargo llvm-cov --all-features --workspace --codecov --output-path codecov.json
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost/postgres
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required for private repos or protected branches
          files: codecov.json
          fail_ci_if_error: true